# Generated by Django 4.2.16 on 2024-09-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationform',
            table='registration_form',
        ),
    ]
